#!/usr/bin/env node
import * as fs from 'fs';
import * as path from 'path';

export type ToolsetVarMeta = {
  key: string;
  provider?: string;
  scope?: string;
  description?: string;
  required: boolean;
  sensitive: boolean;
  targetFile: string;
  default?: string;
  placeholder?: string;
};

export type ToolsetMeta = {
  description?: string;
  files: Record<string, { purpose: string }>;
  vars: ToolsetVarMeta[];
};

export function readToolsetMeta(cwd: string = process.cwd()): ToolsetMeta {
  const metaPath = path.join(cwd, 'config/toolset-env-meta.json');
  return JSON.parse(fs.readFileSync(metaPath, 'utf-8')) as ToolsetMeta;
}

export function renderToolsetFile(
  meta: ToolsetMeta,
  targetFile: string
): string {
  const rows = meta.vars.filter((entry) => entry.targetFile === targetFile);
  const lines = [
    '# Generated by yarn toolset:init',
    `# ${meta.files[targetFile]?.purpose || targetFile}`,
    '',
  ];

  rows.forEach((entry) => {
    const value = entry.default || entry.placeholder || '';
    const annotations = [
      entry.provider ? `provider=${entry.provider}` : '',
      entry.scope ? `scope=${entry.scope}` : '',
      entry.sensitive ? 'secret' : 'plain',
      entry.required ? 'required' : 'optional',
    ].filter(Boolean);

    lines.push(`# ${entry.key} (${annotations.join(', ')})`);
    if (entry.description) {
      lines.push(`# ${entry.description}`);
    }
    lines.push(`${entry.key}=${value}`);
    lines.push('');
  });

  return lines.join('\n');
}

export function writeToolsetFileIfMissing(
  cwd: string,
  relativePath: string,
  content: string
): 'created' | 'skipped' {
  const absolutePath = path.join(cwd, relativePath);
  if (fs.existsSync(absolutePath)) {
    console.log(`skip ${relativePath} (already exists)`);
    return 'skipped';
  }

  fs.writeFileSync(absolutePath, content, 'utf-8');
  console.log(`create ${relativePath}`);
  return 'created';
}

export function runToolsetInit(cwd: string = process.cwd()): void {
  const meta = readToolsetMeta(cwd);

  Object.keys(meta.files).forEach((targetFile) => {
    writeToolsetFileIfMissing(
      cwd,
      targetFile,
      renderToolsetFile(meta, targetFile)
    );
  });
}
