param(
  [ValidateSet("interactive", "doctor", "setup")]
  [string]$Mode = "interactive",
  [switch]$Fix
)

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

function Write-Section {
  param([string]$Title)
  Write-Host ""
  Write-Host "== $Title =="
}

function Test-CommandAvailable {
  param([string]$Name)
  return [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

function Ensure-Directory {
  param([string]$Path)
  if (-not (Test-Path -LiteralPath $Path)) {
    New-Item -ItemType Directory -Force -Path $Path | Out-Null
  }
}

function Add-Finding {
  param(
    [System.Collections.Generic.List[object]]$Findings,
    [string]$Name,
    [bool]$Ok,
    [string]$Detail,
    [string]$FixText = ""
  )

  $Findings.Add([pscustomobject]@{
    Name = $Name
    Ok = $Ok
    Detail = $Detail
    Fix = $FixText
  }) | Out-Null
}

function Ensure-FileFromTemplate {
  param(
    [string]$Path,
    [string]$Template
  )

  if (-not (Test-Path -LiteralPath $Path)) {
    Set-Content -LiteralPath $Path -Value $Template -Encoding UTF8
    return $true
  }

  return $false
}

function Get-FeatureState {
  if (-not (Test-CommandAvailable "codex")) {
    return @()
  }

  $lines = & codex features list 2>$null
  $features = @()
  foreach ($line in $lines) {
    if ($line -match '^\s*([a-zA-Z0-9_]+)\s+([a-zA-Z-]+)\s+(true|false)\s*$') {
      $features += [pscustomobject]@{
        Name = $matches[1]
        Stage = $matches[2]
        Enabled = [System.Convert]::ToBoolean($matches[3])
      }
    }
  }
  return $features
}

function Run-Checks {
  $findings = New-Object 'System.Collections.Generic.List[object]'

  Add-Finding $findings "codex-cli" (Test-CommandAvailable "codex") "Codex CLI is available on PATH." "Install or expose codex.exe on PATH."
  Add-Finding $findings "git" (Test-CommandAvailable "git") "Git is available on PATH." "Install Git."
  Add-Finding $findings "pwsh" (Test-CommandAvailable "pwsh") "PowerShell 7 is available on PATH." "Install PowerShell 7."

  $requiredFiles = @(
    "AGENTS.md",
    "CLAUDE.md",
    ".env.example",
    ".agents\skills\indigo-strapi-standards\SKILL.md",
    ".agents\skills\indigo-ui-registry\SKILL.md",
    "docs\architecture.md",
    "docs\release-gates.md",
    ".codex\environments\environment.toml",
    ".github\PULL_REQUEST_TEMPLATE.md"
  )

  foreach ($file in $requiredFiles) {
    Add-Finding $findings "file:$file" (Test-Path -LiteralPath $file) "$file is present." "Create $file."
  }

  Ensure-Directory ".agents\skills"
  Add-Finding $findings "skills-dir" (Test-Path -LiteralPath ".agents\skills") ".agents\\skills exists." "Create .agents\\skills."

  $mcpOk = $false
  $mcpDetail = ".mcp.json is missing."
  $mcpFix = "Create .mcp.json with valid MCP servers and real secrets handling."
  if (Test-Path -LiteralPath ".mcp.json") {
    $mcpRaw = Get-Content -LiteralPath ".mcp.json" -Raw
    $mcpOk = $mcpRaw -notmatch "your-api-key"
    if ($mcpOk) {
      $mcpDetail = ".mcp.json exists and does not contain the placeholder API key."
      $mcpFix = ""
    } else {
      $mcpDetail = ".mcp.json still contains a placeholder API key value."
    }
  }
  Add-Finding $findings "mcp-config" $mcpOk $mcpDetail $mcpFix

  $features = Get-FeatureState
  if ($features.Count -gt 0) {
    foreach ($featureName in @("apps", "plugins", "multi_agent", "shell_tool")) {
      $feature = $features | Where-Object Name -eq $featureName | Select-Object -First 1
      if ($null -ne $feature) {
        Add-Finding $findings "feature:$featureName" $feature.Enabled "Codex feature '$featureName' enabled = $($feature.Enabled)." "Enable with: codex features enable $featureName"
      }
    }
  } else {
    Add-Finding $findings "codex-features" $false "Could not inspect Codex feature flags." "Run 'codex features list' manually after Codex is installed."
  }

  return $findings
}

function Invoke-Setup {
  Write-Section "Setup"

  Ensure-Directory ".codex\environments"
  Ensure-Directory ".codex\tmp"
  Ensure-Directory ".agents\skills"
  Ensure-Directory "docs"

  $created = @()

  $environmentTemplate = @"
# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "indigo-studio-buildops"

[setup]
script = "yarn dev"

[[actions]]
name = "GitStatus"
icon = "tool"
command = "git status"

[[actions]]
name = "CodexDoctor"
icon = "tool"
command = "pwsh -File scripts/codex-bootstrap.ps1 -Mode doctor"
"@

  if (Ensure-FileFromTemplate -Path ".codex\environments\environment.toml" -Template $environmentTemplate) {
    $created += ".codex\environments\environment.toml"
  }

  $readme = @"
# Repo Skills

Place repo-local Codex team skills here.
"@
  if (Ensure-FileFromTemplate -Path ".agents\skills\README.md" -Template $readme) {
    $created += ".agents\skills\README.md"
  }

  if ($created.Count -eq 0) {
    Write-Host "Repo baseline files already existed."
  } else {
    Write-Host "Created:"
    $created | ForEach-Object { Write-Host "- $_" }
  }
}

function Write-StatusReport {
  param([object[]]$Findings)

  $statusPath = "docs\codex-configuration-status.md"
  $lines = @(
    "# Codex Configuration Status",
    "",
    "- Generated: $(Get-Date -Format s)",
    "",
    "| Check | Status | Detail | Suggested Fix |",
    "|---|---|---|---|"
  )

  foreach ($finding in $Findings) {
    $status = if ($finding.Ok) { "OK" } else { "MISSING" }
    $fix = $finding.Fix -replace '\|', '/'
    $detail = $finding.Detail -replace '\|', '/'
    $lines += "| $($finding.Name) | $status | $detail | $fix |"
  }

  Set-Content -LiteralPath $statusPath -Value ($lines -join [Environment]::NewLine) -Encoding UTF8
  Write-Host "Wrote status report: $statusPath"
}

function Show-Results {
  param([object[]]$Findings)

  Write-Section "Results"
  foreach ($finding in $Findings) {
    $marker = if ($finding.Ok) { "[OK]" } else { "[MISSING]" }
    Write-Host "$marker $($finding.Name): $($finding.Detail)"
    if (-not $finding.Ok -and $finding.Fix) {
      Write-Host "  Fix: $($finding.Fix)"
    }
  }
}

function Run-Doctor {
  $findings = Run-Checks
  Show-Results -Findings $findings
  Write-StatusReport -Findings $findings

  $missing = @($findings | Where-Object { -not $_.Ok })
  if ($missing.Count -eq 0) {
    Write-Host ""
    Write-Host "Codex repo baseline looks healthy."
  } else {
    Write-Host ""
    Write-Host "Codex repo baseline is incomplete."
    if ($Fix) {
      Write-Host "Applying repo-local setup fixes where possible..."
      Invoke-Setup
      $postFindings = Run-Checks
      Show-Results -Findings $postFindings
      Write-StatusReport -Findings $postFindings
    } else {
      Write-Host "Run with -Mode setup or -Fix to scaffold repo-local basics."
    }
  }
}

function Run-Interactive {
  Write-Section "Codex Bootstrap"
  Write-Host "1. Doctor"
  Write-Host "2. Setup repo-local basics"
  Write-Host "3. Doctor and fix what can be fixed"
  $choice = Read-Host "Choose an option"

  switch ($choice) {
    "1" { Run-Doctor }
    "2" { Invoke-Setup; Run-Doctor }
    "3" { $script:Fix = $true; Run-Doctor }
    default { throw "Invalid selection: $choice" }
  }
}

switch ($Mode) {
  "doctor" { Run-Doctor }
  "setup" { Invoke-Setup; Run-Doctor }
  "interactive" { Run-Interactive }
}
